-- MySQL Script generated by MySQL Workbench
-- Sáb 28 Abr 2018 18:35:51 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema LordOfFlorestal
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `LordOfFlorestal` ;

-- -----------------------------------------------------
-- Schema LordOfFlorestal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LordOfFlorestal` DEFAULT CHARACTER SET utf8 ;
USE `LordOfFlorestal` ;

-- -----------------------------------------------------
-- Table `LordOfFlorestal`.`SubtipoCarta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LordOfFlorestal`.`SubtipoCarta` ;

CREATE TABLE IF NOT EXISTS `LordOfFlorestal`.`SubtipoCarta` (
  `id_subtipo_carta` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_subtipo_carta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LordOfFlorestal`.`TipoCarta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LordOfFlorestal`.`TipoCarta` ;

CREATE TABLE IF NOT EXISTS `LordOfFlorestal`.`TipoCarta` (
  `id_tipo_carta` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_carta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LordOfFlorestal`.`Carta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LordOfFlorestal`.`Carta` ;

CREATE TABLE IF NOT EXISTS `LordOfFlorestal`.`Carta` (
  `id_carta` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `imagem` LONGBLOB NOT NULL,
  `efeito` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `valor_ataque` INT NULL,
  `valor_defesa` INT NULL,
  `id_tipo_carta` INT NOT NULL,
  `id_subtipo_carta` INT NOT NULL,
  PRIMARY KEY (`id_carta`),
  INDEX `fk_Carta_SubtipoCarta1_idx` (`id_subtipo_carta` ASC),
  INDEX `fk_Carta_TipoCarta1_idx` (`id_tipo_carta` ASC),
  CONSTRAINT `fk_Carta_SubtipoCarta1`
    FOREIGN KEY (`id_subtipo_carta`)
    REFERENCES `LordOfFlorestal`.`SubtipoCarta` (`id_subtipo_carta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carta_TipoCarta1`
    FOREIGN KEY (`id_tipo_carta`)
    REFERENCES `LordOfFlorestal`.`TipoCarta` (`id_tipo_carta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LordOfFlorestal`.`ValeCarta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LordOfFlorestal`.`ValeCarta` ;

CREATE TABLE IF NOT EXISTS `LordOfFlorestal`.`ValeCarta` (
  `codigo` VARCHAR(45) NOT NULL,
  `valido` TINYINT(1) NOT NULL DEFAULT 1,
  `id_carta` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_ValeCarta_Carta1_idx` (`id_carta` ASC),
  CONSTRAINT `fk_ValeCarta_Carta1`
    FOREIGN KEY (`id_carta`)
    REFERENCES `LordOfFlorestal`.`Carta` (`id_carta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LordOfFlorestal`.`TipoJogador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LordOfFlorestal`.`TipoJogador` ;

CREATE TABLE IF NOT EXISTS `LordOfFlorestal`.`TipoJogador` (
  `id_tipo_jogador` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipo_jogador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LordOfFlorestal`.`Badge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LordOfFlorestal`.`Badge` ;

CREATE TABLE IF NOT EXISTS `LordOfFlorestal`.`Badge` (
  `id_badge` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(100) NULL,
  `imagem` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_badge`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LordOfFlorestal`.`Jogador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LordOfFlorestal`.`Jogador` ;

CREATE TABLE IF NOT EXISTS `LordOfFlorestal`.`Jogador` (
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `imagem` VARCHAR(45) NULL DEFAULT '"user.png"',
  `matricula` INT NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `ano_admissao` INT NOT NULL DEFAULT 0,
  `id_tipo_jogador` INT NOT NULL,
  `num_jogos` INT NOT NULL DEFAULT 0,
  `num_jogos_ganho` INT NOT NULL DEFAULT 0,
  `num_jogos_perdido` INT NOT NULL DEFAULT 0,
  `num_jogos_ganhou_lord` INT NOT NULL DEFAULT 0,
  `num_jogos_perdeu_lord` INT NOT NULL DEFAULT 0,
  `xp` INT NOT NULL,
  `id_badge` INT NOT NULL,
  INDEX `fk_Jogador_TipoJogador1_idx` (`id_tipo_jogador` ASC),
  PRIMARY KEY (`matricula`),
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_Jogador_Badge1_idx` (`id_badge` ASC),
  CONSTRAINT `fk_Jogador_TipoJogador1`
    FOREIGN KEY (`id_tipo_jogador`)
    REFERENCES `LordOfFlorestal`.`TipoJogador` (`id_tipo_jogador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jogador_Badge1`
    FOREIGN KEY (`id_badge`)
    REFERENCES `LordOfFlorestal`.`Badge` (`id_badge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LordOfFlorestal`.`SituacaoDuelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LordOfFlorestal`.`SituacaoDuelo` ;

CREATE TABLE IF NOT EXISTS `LordOfFlorestal`.`SituacaoDuelo` (
  `id_situacao_carta` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_situacao_carta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LordOfFlorestal`.`Duelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LordOfFlorestal`.`Duelo` ;

CREATE TABLE IF NOT EXISTS `LordOfFlorestal`.`Duelo` (
  `id_duelo` INT NOT NULL AUTO_INCREMENT,
  `uri` VARCHAR(10) NOT NULL,
  `criador` INT NOT NULL,
  `oponente` INT NULL,
  `vencedor` INT NULL,
  `id_situacao_duelo` INT NOT NULL,
  `data_criacao` DATETIME NOT NULL,
  `pontos_determinacao_vencedor` INT NULL DEFAULT 0,
  `pontos_determinacao_perdedor` INT NULL DEFAULT 0,
  PRIMARY KEY (`id_duelo`),
  INDEX `fk_Duelo_SituacaoDuelo1_idx` (`id_situacao_duelo` ASC),
  INDEX `fk_Duelo_Jogador1_idx` (`criador` ASC),
  INDEX `fk_Duelo_Jogador2_idx` (`oponente` ASC),
  INDEX `fk_Duelo_Jogador3_idx` (`vencedor` ASC),
  CONSTRAINT `fk_Duelo_SituacaoDuelo1`
    FOREIGN KEY (`id_situacao_duelo`)
    REFERENCES `LordOfFlorestal`.`SituacaoDuelo` (`id_situacao_carta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Duelo_Jogador1`
    FOREIGN KEY (`criador`)
    REFERENCES `LordOfFlorestal`.`Jogador` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Duelo_Jogador2`
    FOREIGN KEY (`oponente`)
    REFERENCES `LordOfFlorestal`.`Jogador` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Duelo_Jogador3`
    FOREIGN KEY (`vencedor`)
    REFERENCES `LordOfFlorestal`.`Jogador` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LordOfFlorestal`.`Deck`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LordOfFlorestal`.`Deck` ;

CREATE TABLE IF NOT EXISTS `LordOfFlorestal`.`Deck` (
  `id_deck` INT NOT NULL AUTO_INCREMENT,
  `matricula_jogador` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_deck`),
  INDEX `fk_Deck_Jogador1_idx` (`matricula_jogador` ASC),
  CONSTRAINT `fk_Deck_Jogador1`
    FOREIGN KEY (`matricula_jogador`)
    REFERENCES `LordOfFlorestal`.`Jogador` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LordOfFlorestal`.`Jogador_has_Carta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LordOfFlorestal`.`Jogador_has_Carta` ;

CREATE TABLE IF NOT EXISTS `LordOfFlorestal`.`Jogador_has_Carta` (
  `matricula_jogador` INT NOT NULL,
  `id_carta` INT NOT NULL,
  PRIMARY KEY (`matricula_jogador`, `id_carta`),
  INDEX `fk_Jogador_has_Carta_Carta1_idx` (`id_carta` ASC),
  INDEX `fk_Jogador_has_Carta_Jogador1_idx` (`matricula_jogador` ASC),
  CONSTRAINT `fk_Jogador_has_Carta_Jogador1`
    FOREIGN KEY (`matricula_jogador`)
    REFERENCES `LordOfFlorestal`.`Jogador` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jogador_has_Carta_Carta1`
    FOREIGN KEY (`id_carta`)
    REFERENCES `LordOfFlorestal`.`Carta` (`id_carta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LordOfFlorestal`.`Missao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LordOfFlorestal`.`Missao` ;

CREATE TABLE IF NOT EXISTS `LordOfFlorestal`.`Missao` (
  `id_missao` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(200) NOT NULL,
  `id_carta` INT NOT NULL,
  `ativa` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_missao`),
  INDEX `fk_Missao_Carta1_idx` (`id_carta` ASC),
  CONSTRAINT `fk_Missao_Carta1`
    FOREIGN KEY (`id_carta`)
    REFERENCES `LordOfFlorestal`.`Carta` (`id_carta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LordOfFlorestal`.`Deck_has_Carta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LordOfFlorestal`.`Deck_has_Carta` ;

CREATE TABLE IF NOT EXISTS `LordOfFlorestal`.`Deck_has_Carta` (
  `id_carta` INT NOT NULL,
  `id_deck` INT NOT NULL,
  PRIMARY KEY (`id_carta`, `id_deck`),
  INDEX `fk_Carta_has_Deck_Deck1_idx` (`id_deck` ASC),
  INDEX `fk_Carta_has_Deck_Carta1_idx` (`id_carta` ASC),
  CONSTRAINT `fk_Carta_has_Deck_Carta1`
    FOREIGN KEY (`id_carta`)
    REFERENCES `LordOfFlorestal`.`Carta` (`id_carta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carta_has_Deck_Deck1`
    FOREIGN KEY (`id_deck`)
    REFERENCES `LordOfFlorestal`.`Deck` (`id_deck`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LordOfFlorestal`.`Jogador_has_Badge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LordOfFlorestal`.`Jogador_has_Badge` ;

CREATE TABLE IF NOT EXISTS `LordOfFlorestal`.`Jogador_has_Badge` (
  `matricula_jogador` INT NOT NULL,
  `id_badge` INT NOT NULL,
  PRIMARY KEY (`matricula_jogador`, `id_badge`),
  INDEX `fk_Badge_has_Jogador_Jogador1_idx` (`matricula_jogador` ASC),
  INDEX `fk_Badge_has_Jogador_Badge1_idx` (`id_badge` ASC),
  CONSTRAINT `fk_Badge_has_Jogador_Badge1`
    FOREIGN KEY (`id_badge`)
    REFERENCES `LordOfFlorestal`.`Badge` (`id_badge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Badge_has_Jogador_Jogador1`
    FOREIGN KEY (`matricula_jogador`)
    REFERENCES `LordOfFlorestal`.`Jogador` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `LordOfFlorestal` ;

-- -----------------------------------------------------
-- Placeholder table for view `LordOfFlorestal`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LordOfFlorestal`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `LordOfFlorestal`.`view1`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `LordOfFlorestal`.`view1` ;
DROP TABLE IF EXISTS `LordOfFlorestal`.`view1`;
USE `LordOfFlorestal`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
